### PR TITLE
support times with more than 24 hours

### PR DESCRIPTION
**Pull request by bwaldvogel**
#### Example
`27:17:54` cannot be represented by `datetime.time`.
Fallback to `datetime.timedelta` in this case.

### CODE REVIEW

**Comment by chfw** [comment]
Thanks for your patch. I will merge them. Could you please name one use case that needs this patch?

**Comment by bwaldvogel** [comment]
Use case: A duration that is formatted with HH:MM:SS

**Comment by bwaldvogel** [comment]
Is there a release planned that will contain this improvement?

**Comment by chfw** [comment]
I am sorry. I should have put a note here and in the release note.

Yes, it is released together with 0.1.0. You should be able to get it via pypi now.

**Comment by bwaldvogel** [comment]
Thanks. Works like a charm.

**Pull request merged**
